# Generated by Django 6.0.2 on 2026-03-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model("core", "Project")
            .objects.filter(title="Customer Behaviour Analysis")
            .update(slug="customer-behaviour-analysis")
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model("core", "Project")
            .objects.filter(title="Multimodal Sentiment Analysis")
            .update(slug="multimodal-sentiment-analysis")
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model("core", "Project")
            .objects.filter(title="Real-Time QR Code System")
            .update(slug="real-time-qr-code-system")
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model("core", "Project")
            .objects.filter(title="Predictive Analytics Dashboard")
            .update(slug="predictive-analytics-dashboard")
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE core_project SET slug = 'customer-behaviour-analysis' WHERE title = 'Customer Behaviour Analysis';
                UPDATE core_project SET slug = 'multimodal-sentiment-analysis' WHERE title = 'Multimodal Sentiment Analysis';
                UPDATE core_project SET slug = 'real-time-qr-code-system' WHERE title = 'Real-Time QR Code System';
                UPDATE core_project SET slug = 'predictive-analytics-dashboard' WHERE title = 'Predictive Analytics Dashboard';
            """,
            reverse_sql="",
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
