# Generated by Django 4.2.9 on 2026-04-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_slug_alter_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('analysis', 'Analysis'), ('development', 'Development')], default='development', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='detailed_description',
            field=models.TextField(blank=True),
        ),
    ]
